### ISSUE TITLE
Tables either missing or import went wrong

### ISSUE THREAD

**Issue by JakeChampion** [igrigorik/httparchive#1]
I wanted to run queries on the last 2 years of page data and found some missing tables/data.
Posting here as to not lose this information: https://twitter.com/igrigorik/status/577158258000953344

2013_07_15_pages does not exist
2013_12_01_pages does not exist
2014_12_01_pages 0 rows
2014_03_15_pages 0 rows

**Comment by igrigorik** [comment]
@souders @pmeenan what happened to the list of crawl archives on [HTTPArchive downloads page](http://httparchive.org/downloads.php)? Is there a bug?

- http://archive.org/download/httparchive_downloads_Jul_15_2013/httparchive_Jul_15_2013_pages.csv.gz
- http://archive.org/download/httparchive_downloads_Dec_01_2013/httparchive_Dec_01_2013_pages.csv.gz
- http://archive.org/download/httparchive_downloads_Dec_01_2014/httparchive_Dec_01_2014_pages.csv.gz

^ above three return 404's; can't import them. The 2014_03_15 import is running now.

**Comment by pmeenan** [comment]
Hmm, possibly some dev work Steve is doing to split things up.  You can see
the crawl list on the "dev" version of the site (where they are actually
kept - long story): http://dev.httparchive.org/downloads.php

I'll have to reach out to the IA team to ask them about the 404's.  It
looks like the 404 pages are complaining about errors with the meta-data so
hopefully it's just a container problem and not a problem with the actual
data (though I think we can re-generate the pages dumps easily since we
keep them on the server).

**Comment by stevesouders** [comment]
Just a bug. Should be fixed now.

I started work to spin up the Chrome and mobile emulation crawls. Introducing these new (parallel) crawls caused some settings to get blanked out but should be good.
